### ISSUE TITLE
Uploader not working with QTPy ESP32 Pico

### ISSUE THREAD

**Issue by brentru** [adafruit/WipperSnapper_Firmware_Uploader#17]
@lorennorman  The uploader is not working with a QtPy ESP32 Pico, I'm unsure why.

<img width="582" alt="image" src="https://user-images.githubusercontent.com/322428/170735269-410b312d-b795-4c31-b685-9c757ac79c6a.png">

**Comment by brentru** [comment]
Might be due to the QTPy Pico not being added to the board map:

https://github.com/adafruit/WipperSnapper_Firmware_Uploader/blob/5d0b32970a5dfa772d8bfff5a439f69c7abf5f4d/js/script.js#L13

@makermelissa  Would this be the problem? I can make the modification and PR if that's the case.

**Comment by lorennorman** [comment]
Oh yep I bet that’s it Brent. Looks like I never removed the “daily” thing
from there either.

**Comment by brentru** [comment]
Working with #18, closed.
